// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    url: "postgres://3c66abf20c6e4a882990dea72db0cfef7c045dcee65db233524bcaa84e7645dd:sk_sXlVaBhw-g2JUyLWviugh@db.prisma.io:5432/postgres?sslmode=require",
  },
});
